server:
  port: 8082

#dataSource
spring:
  datasource:
    url: "jdbc:mysql://119.29.115.175:3306/girl"
    driver-class-name: "com.mysql.jdbc.Driver"
    username: "root"
    password: "1234qwerQWER!@#$"

#页面前缀后缀
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp

#mybatis

